apiVersion: 1

datasources:
  # OpenObserve via Elasticsearch-compatible API
  - name: OpenObserve
    type: elasticsearch
    access: proxy
    url: http://openobserve:5080/api/default/
    isDefault: true
    editable: false
    jsonData:
      index: "default"
      timeField: "_timestamp"
      esVersion: "7.10.0"
    basicAuth: true
    basicAuthUser: admin@maltbox.local
    secureJsonData:
      basicAuthPassword: admin
